### ISSUE TITLE
Magic user config.js missing

### ISSUE THREAD

**Issue by j94305** [dtylman/AWSRetriever#2]
First of all, AWSRetriever is a really nice and nifty tool. Congratulations!

There was some magic involved with setting up config.js. The option "-c" is not documented, and I could not find a description of the config file syntax. It would be helpful to include that in the documentation, or to default to accessing some ~/.aws/config file instead.

**Comment by dtylman** [comment]
Thanks for the warm words! Its great you find this useful.

I have started this project over a year ago. Nowadays I don't think it has too many users and unfortunately I no longer have time to maintain it :(

Feel free to open a pull-request with the changes.
